AWSTemplateFormatVersion: '2010-09-09'
Description: Basic template to create an EC2 instance and an S3 bucket

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-05e1fab70426e6fd9  # Update with your desired AMI ID
      InstanceType: t2.micro
      KeyName: training-key
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: Shivathmika-instance

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: shivatmika21-s3-bucket
